### ISSUE TITLE
(2.7) Implement `equals()` method

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-mrbean#22]
It would make sense to implement `equals()`, at least for interfaces, and for abstract classes that do not define `equals()` for target type.

Basic implementation should simply compare all logical properties using the typical implementation that an IDE would produce (field-by-field comparison).

**Comment by asaf-romano** [comment]
Hi, was this change reverted at some point. It deosn't work for me in the latest version. That is, `eqauls` returns false when comparing two objects deseralized from the same json string.

**Comment by asaf-romano** [comment]
Oops, didn't realize this was closed during github project migration.
https://github.com/FasterXML/jackson-modules-base/issues/3
