### ISSUE TITLE
JsonMappingException: Can not instantiate value of type [simple type, ]from Integral number (60); no single-int-arg constructor/factory method

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [FasterXML/jackson-module-mrbean#24]
Hello,
I am using msgpack to serialize/deserialize objects 
```
<!-- MsgPack dependency -->
 		<dependency>
			<groupId>org.msgpack</groupId>
			<artifactId>jackson-dataformat-msgpack</artifactId>
			<version>0.7.0-p5</version>
		</dependency>
```
which internally uses the following version 2.4.4 of jackson-core ,2.4.0. for jackson-databind.

I am experiencing a strange problem i am getting the following exception when running the jar on linux machine
```
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class xxx] from Integral number (60); no single-int-arg constructor/factory method
at [Source: [B@2f33e642; line: -1, column: 0]
       at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:770) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:310) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1098) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:137) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066) ~[jackson-databind-2.4.4.jar:2.4.4]
       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2230) ~[jackson-databind-2.4.4.jar:2.4.4]
       at cxxx.xxxSerializer.deserialize(xxxSerializer.java:100) [vsb-em.jar:?]
```

The problem is it has final property due to which i can't have no argument constructor so i used the following annotations on the constructor
```
@JsonCreator
and on property @JsonProperty
```
and it works fine on my windows machine. 
Please let me know why this is happening and what is the solution over it.

**Comment by cowtowncoder** [comment]
That does sound odd. To reproduce this, I would need a test to reproduce unfortunately, since I can't think of any straight-forward reason for it.

You also want to try upgrade to Jackson 2.5.4 just in case; some bug fixes since 2.4.4 may be relevant.

**Comment by Anand-J-Kadhi** [comment]
Ya but i am using ObjectMapper to pass msgpack instance which internally uses jackson-core 2.4.4. 
```
 <dependency>
            <groupId>org.msgpack</groupId>
            <artifactId>jackson-dataformat-msgpack</artifactId>
            <version>0.7.0-p5</version>
        </dependency>
```
I am not sure which objectMapper dependency uses 2.5.4 internally can you please share if you have any info about it.

**Comment by cowtowncoder** [comment]
I suggested use of a later version just to see if it might be due to a bug that has been fixed; I can not think of specific reason why the problem occurs.

But I can not do much more without reproducible test case. Error message itself indicates that JSON content encountered for value of type `xxx` is a JSON Number, but `xxx` is not designed to bind from JSON Number. Without knowing what type `xxx` it is difficult to say much more, except to guess that maybe it is just a POJO, in which case its JSON representation should be a JSON Object.

**Comment by Anand-J-Kadhi** [comment]
Hi @cowtowncoder ,

I upgraded to version 2.5.3 as suggested, but still i am facing the same issue. There is no int value when the object is serialized but i am not having any clue as why this is happening. I am still getting the same error message. The class has some final variables could that be an issue?

**Comment by cowtowncoder** [comment]
At this point I can not reproduce the problem so there isn't much I can do -- it is not clear from just error message what might be happening; and even I changed something I could not verify it helps.
Whether final fields matter I don't know.

**Comment by Anand-J-Kadhi** [comment]
Ok thanks @cowtowncoder for your inputs

**Comment by Anand-J-Kadhi** [comment]
Hi @cowtowncoder ,

Please ignore the strange issue i am talking about, on analysis i found that the byte data which was processed was serialized using xml serializer(XstreamSerializer) so it was complaining about code 60 which stands for '<' which is the starting of the xml document.
Sorry for the inconvenience caused.

**Comment by cowtowncoder** [comment]
Ah! No problem -- I'd rather hear about what seem like problems, than ignore things just to avoid occasional false alarm. Just glad you figured it out and updated the issue so we know it is not a Jackson issue.
